### ISSUE TITLE
Please add complete authorship information in DESCRIPTION

### ISSUE THREAD

**Issue by jranke** [saemixdevelopment/saemix#1]
I wonder why the three authors given in the CRAN version have been deleted from the Authors field?

Also, comparison of the CHANGES file between this repo and CRAN/saemix suggests that the changes to make saemix compatible with R 4.0.0 that have been published on CRAN as version 2.3 have not been merged here?

**Comment by BelhalK** [comment]
Authors changed and code updated to reflect CRAN.
